set_property PACKAGE_PIN W5 [get_ports CLK]
    set_property IOSTANDARD LVCMOS33 [get_ports CLK]
    
set_property PACKAGE_PIN G2 [get_ports IRLed]
    set_property IOSTANDARD LVCMOS33 [get_ports IRLed]
    
set_property PACKAGE_PIN E19 [get_ports {CarSelectOut[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CarSelectOut[0]}]
set_property PACKAGE_PIN U19 [get_ports {CarSelectOut[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CarSelectOut[1]}]
    
    
set_property PACKAGE_PIN V16 [get_ports {CarSelectIn[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CarSelectIn[0]}]
set_property PACKAGE_PIN W16 [get_ports {CarSelectIn[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CarSelectIn[1]}]
    
set_property PACKAGE_PIN T17 [get_ports {Command[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Command[3]}]
set_property PACKAGE_PIN W19 [get_ports {Command[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Command[2]}]
set_property PACKAGE_PIN U17 [get_ports {Command[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Command[1]}]
set_property PACKAGE_PIN T18 [get_ports {Command[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Command[0]}]
    
    
    
set_property PACKAGE_PIN W7 [get_ports {SegmentDisplayOut[6]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {SegmentDisplayOut[6]}]
set_property PACKAGE_PIN W6 [get_ports {SegmentDisplayOut[5]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {SegmentDisplayOut[5]}]
set_property PACKAGE_PIN U8 [get_ports {SegmentDisplayOut[4]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {SegmentDisplayOut[4]}]
set_property PACKAGE_PIN V8 [get_ports {SegmentDisplayOut[3]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {SegmentDisplayOut[3]}]
set_property PACKAGE_PIN U5 [get_ports {SegmentDisplayOut[2]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {SegmentDisplayOut[2]}]
set_property PACKAGE_PIN V5 [get_ports {SegmentDisplayOut[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {SegmentDisplayOut[1]}]
set_property PACKAGE_PIN U7 [get_ports {SegmentDisplayOut[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {SegmentDisplayOut[0]}]
set_property PACKAGE_PIN U2 [get_ports {SegmentDisplayAnodeActivate[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {SegmentDisplayAnodeActivate[0]}]
set_property PACKAGE_PIN U4 [get_ports {SegmentDisplayAnodeActivate[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {SegmentDisplayAnodeActivate[1]}]
set_property PACKAGE_PIN V4 [get_ports {SegmentDisplayAnodeActivate[2]}]               
   set_property IOSTANDARD LVCMOS33 [get_ports {SegmentDisplayAnodeActivate[2]}]
set_property PACKAGE_PIN W4 [get_ports {SegmentDisplayAnodeActivate[3]}]          
   set_property IOSTANDARD LVCMOS33 [get_ports {SegmentDisplayAnodeActivate[3]}]